### ISSUE TITLE
Action placement in RTL mode

### ISSUE THREAD

**Issue by Farzin-Firoozi** [iamhosseindhv/notistack#607]
## Expected Behavior
In RTL mode the actions needs to be aligned to the left

## Current Behavior
<img width="318" alt="image" src="https://github.com/user-attachments/assets/0445f762-c13c-4a5a-9ba0-7bef4fe57b00">

Here's the code:

```tsx
const MUIProvider: FC<PropsWithChildren> = ({ children }) => {
  return (
    <body className={IranSansFont.className} dir="rtl">
      <AppRouterCacheProvider
        options={{
          key: 'muirtl',
          stylisPlugins: [stylisRTLPlugin],
        }}
      >
        <ThemeProvider theme={theme}>
          <SnackbarProvider
            dense
            preventDuplicate
            anchorOrigin={{
              vertical: 'top',
              horizontal: 'center',
            }}
            action={(key) => (
              <IconButton onClick={() => closeSnackbar(key)}>
                <RiCloseLine color="white" />
              </IconButton>
            )}
          >
            {children}
          </SnackbarProvider>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </body>
  )
}
```

## Your Environment
 ```json
 "dependencies": {
    "@emotion/cache": "^11.13.0",
    "@emotion/react": "^11.13.0",
    "@emotion/styled": "^11.13.0",
    "@mui/material": "^5.16.4",
    "@mui/material-nextjs": "^5.16.4",
    "@remixicon/react": "^4.2.0",
    "@tanstack/react-query": "^5.51.15",
    "@tanstack/react-query-devtools": "^5.51.15",
    "axios": "^1.7.2",
    "next": "14.2.5",
    "notistack": "^3.0.1",
    "react": "^18",
    "react-dom": "^18",
    "recoil": "^0.7.7",
    "recoil-persist": "^5.1.0",
    "stylis": "^4.3.2",
    "stylis-plugin-rtl": "^2.1.1"
  }
  ```

**Comment by Rezaabdi78** [comment]
Hi, Farzin.

I have the same problem with styling action button in snackbar shown.

I have solved it through className and CSS overriding like this:

in my global.scss:
```scss
.notistack-MuiContent-<variant_name>: {},
// this is the content container selector for every type of snacks  
.notistack-MuiContent {
// I think you need to add justify-content:space-between in your case
        // this is the action button selector
	& > :nth-child(2) {
		margin-left: -0.5rem;
		margin-right: 0rem;
		padding-right: 1rem;
		padding-left: 0;
	}
}
```
